name: iOS CI

on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        run: |
          xcodebuild test \
            -project swiftDataToDo/swiftDataToDo.xcodeproj \
            -scheme swiftDataToDo \
            -destination 'platform=iOS Simulator,name=iPhone 17 Pro,OS=latest' \
            -resultBundlePath TestResults