name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: List available simulators (debug)
        run: xcrun simctl list devices available

      - name: Run tests
        run: |
          xcodebuild test \
            -project SwiftData-ToDo-Practice/swiftDataToDo/swiftDataToDo.xcodeproj \
            -scheme swiftDataToDo \
            -destination "generic/platform=iOS Simulator" \
            -resultBundlePath TestResults